const SERVICES=[
{id:'property',title:'مدیریت کامل ملک',group:'ملک',tier:'free',actions:['create','view','edit','delete','archive','duplicate','publish','refresh']},
{id:'search',title:'جست‌وجوی هوشمند',group:'جست‌وجو',tier:'free',actions:['search','filter','map','save','alert']},
{id:'advisor',title:'مشاور AI املاک',group:'هوش مصنوعی',tier:'plus',actions:['analyze','compare','recommend','negotiate']},
{id:'matching',title:'تطبیق هوشمند',group:'هوش مصنوعی',tier:'pro',actions:['match','rank','explain']},
{id:'property-intel',title:'هوش ملک و قیمت',group:'تحلیل',tier:'pro',actions:['valuation','price_check','risk','history']},
{id:'trust',title:'Trust Engine',group:'اعتماد',tier:'pro',actions:['verify','score','flag','provenance']},
{id:'location',title:'Location Intelligence',group:'موقعیت',tier:'pro',actions:['map','nearby','route','area_analysis']},
{id:'measurement',title:'نقشه و اندازه‌گیری',group:'موقعیت',tier:'pro',actions:['measure','boundary','export_pdf','qr']},
{id:'project',title:'تبدیل ملک به پروژه',group:'پروژه',tier:'pro',actions:['create','version','team','share']},
{id:'construction',title:'AI Construction Studio',group:'ساخت',tier:'pro',actions:['feasibility','cost','unit_mix','economics']},
{id:'design',title:'AI Design Studio',group:'ساخت',tier:'pro',actions:['plan','facade','interior','renovation','landscape']},
{id:'investment',title:'Investment Intelligence',group:'سرمایه‌گذاری',tier:'pro',actions:['roi','scenario','risk','compare']},
{id:'content',title:'AI Content Studio',group:'بازاریابی',tier:'pro',actions:['listing_copy','social','reels','brochure','campaign']},
{id:'crm',title:'CRM حرفه‌ای',group:'دفتر',tier:'pro',actions:['customer','pipeline','followup','daily_plan']},
{id:'customer-intel',title:'Customer Intelligence',group:'دفتر',tier:'pro',actions:['lead_score','intent','routing','followup']},
{id:'communications',title:'ارتباطات',group:'ارتباطات',tier:'pro',actions:['chat','message','viewing','share']},
{id:'documents',title:'مدیریت اسناد',group:'اسناد',tier:'pro',actions:['upload','extract','verify','version','compare']},
{id:'contracts',title:'قرارداد دیجیتال',group:'معامله',tier:'pro',actions:['create','version','sign','history']},
{id:'transactions',title:'مدیریت معامله',group:'معامله',tier:'office',actions:['sale','rent','presale','partnership','investment']},
{id:'notifications',title:'مرکز اعلان',group:'ارتباطات',tier:'pro',actions:['push','email','sms','whatsapp','alerts']},
{id:'reports',title:'داشبورد و گزارش',group:'دفتر',tier:'pro',actions:['sales','revenue','agents','market','ai']},
{id:'integrations',title:'اتصال به سرویس‌ها',group:'اتصال',tier:'office',actions:['api','import','export','webhook']},
{id:'media',title:'Media & Virtual Tour',group:'رسانه',tier:'pro',actions:['photo','video','360','tour','render']},
{id:'lead-scout',title:'Lead Scout',group:'هوش مصنوعی',tier:'pro',actions:['scan','dedupe','track','report']},
{id:'market',title:'Market Intelligence',group:'تحلیل',tier:'pro',actions:['scan','trend','area_report','opportunity']},
{id:'qa',title:'AI QA & Self-Healing',group:'سیستم',tier:'office',actions:['health','test','propose_fix','approval','rollback']},
{id:'billing',title:'اشتراک و شارژ',group:'حساب',tier:'free',actions:['plan','upgrade','topup','invoice']},
{id:'security',title:'امنیت و دسترسی',group:'سیستم',tier:'office',actions:['roles','permissions','audit','sessions']},
{id:'future',title:'اتصال‌های آینده',group:'آینده',tier:'enterprise',actions:['finance','legal','identity','3d','vr','ar','satellite','digital_twin']}
];
module.exports={SERVICES};