const express=require('express');
const session=require('express-session');
const bcrypt=require('bcryptjs');
const fs=require('fs'); const path=require('path');
const crypto=require('crypto');
const app=express();
const PORT=Number(process.env.PORT||10000);
const DB_FILE=process.env.DATA_FILE||path.join(__dirname,'data.json');
const SCHEMA_VERSION=2;
const empty=()=>({schema_version:SCHEMA_VERSION,staff:[],properties:[],clients:[],followups:[],activities:[],seq:{staff:1,properties:1,clients:1,followups:1,activities:1}});
function load(){try{const d=JSON.parse(fs.readFileSync(DB_FILE,'utf8')); const e=empty(); return {...e,...d,seq:{...e.seq,...(d.seq||{})},activities:d.activities||[]};}catch{return empty()}}
let store=load();
function save(){const tmp=DB_FILE+'.tmp'; fs.writeFileSync(tmp,JSON.stringify(store,null,2)); fs.renameSync(tmp,DB_FILE)}
function next(k){const n=Number(store.seq[k]||1); store.seq[k]=n+1; return n}
function now(){return new Date().toISOString()}
function clean(v){return String(v??'').trim()}
function actor(req){return req.session.user||null}
function audit(req,action,entity,entityId,details=''){const u=actor(req); if(!u)return; store.activities.push({id:next('activities'),user_id:u.id,user_name:u.name,action,entity,entity_id:entityId,details,created_at:now()}); if(store.activities.length>10000)store.activities=store.activities.slice(-10000); save()}
app.use(express.json({limit:'10mb'}));
app.use(express.urlencoded({extended:true}));
app.set('trust proxy', 1);
app.use(session({secret:process.env.SESSION_SECRET||'change-this-secret',resave:false,saveUninitialized:false,cookie:{httpOnly:true,secure:process.env.NODE_ENV==='production',sameSite:'lax',maxAge:1000*60*60*24*14}}));
function auth(req,res,next){if(!req.session.user)return res.status(401).json({error:'AUTH_REQUIRED'});next()}
function admin(req,res,next){if(req.session.user?.role!=='admin')return res.status(403).json({error:'ADMIN_REQUIRED'});next()}
function staffOnly(req,res,next){if(!req.session.user)return res.status(401).json({error:'AUTH_REQUIRED'});next()}
function visibleForUser(items,req){if(req.session.user.role==='admin')return items; return items.filter(x=>!x.assigned_to||Number(x.assigned_to)===Number(req.session.user.id))}
function init(){const email=clean(process.env.ADMIN_EMAIL),pass=String(process.env.ADMIN_PASSWORD||''); if(email&&pass&&!store.staff.some(x=>String(x.email).toLowerCase()===email.toLowerCase())){store.staff.push({id:next('staff'),name:'مدیر دفتر',email,password_hash:bcrypt.hashSync(pass,12),role:'admin',active:true,created_at:now()});save()}}
init();
app.get('/api/health',(req,res)=>res.json({ok:true,version:SCHEMA_VERSION,storage:'json',time:now()}));
app.post('/api/login',async(req,res)=>{const email=clean(req.body?.email),password=String(req.body?.password||'');const a=store.staff.find(x=>x.active&&String(x.email).toLowerCase()===email.toLowerCase());if(!a||!(await bcrypt.compare(password,a.password_hash)))return res.status(401).json({error:'ایمیل یا رمز عبور اشتباه است'});req.session.user={id:a.id,name:a.name,email:a.email,role:a.role};audit(req,'login','session',a.id,'ورود به سیستم');res.json(req.session.user)});
app.post('/api/logout',(req,res)=>{const u=req.session.user; req.session.destroy(()=>{if(u){store.activities.push({id:next('activities'),user_id:u.id,user_name:u.name,action:'logout',entity:'session',entity_id:u.id,details:'خروج از سیستم',created_at:now()});save()}res.json({ok:true})})});
app.get('/api/me',auth,(req,res)=>res.json(req.session.user));
app.get('/api/staff',admin,(req,res)=>res.json(store.staff.map(({password_hash,...x})=>x).sort((a,b)=>a.name.localeCompare(b.name,'fa'))));
app.post('/api/staff',admin,(req,res)=>{const name=clean(req.body?.name),email=clean(req.body?.email),password=String(req.body?.password||'');if(!name||!email||password.length<6)return res.status(400).json({error:'نام، ایمیل و رمز حداقل ۶ کاراکتر لازم است'});if(store.staff.some(x=>x.email.toLowerCase()===email.toLowerCase()))return res.status(409).json({error:'این ایمیل قبلاً ثبت شده است'});const x={id:next('staff'),name,email,password_hash:bcrypt.hashSync(password,12),role:req.body.role==='admin'?'admin':'staff',active:true,created_at:now()};store.staff.push(x);save();audit(req,'create','staff',x.id,`ایجاد کاربر ${x.name}`);const {password_hash,...safe}=x;res.json(safe)});
app.patch('/api/staff/:id',admin,(req,res)=>{const x=store.staff.find(s=>s.id==req.params.id);if(!x)return res.status(404).json({error:'کاربر پیدا نشد'});if(req.body.name)x.name=clean(req.body.name);if(req.body.email)x.email=clean(req.body.email);if(req.body.role)x.role=req.body.role==='admin'?'admin':'staff';if(typeof req.body.active==='boolean'){if(x.role==='admin'&&req.body.active===false&&store.staff.filter(s=>s.role==='admin'&&s.active).length<=1)return res.status(400).json({error:'حداقل یک مدیر فعال باید باقی بماند'});x.active=req.body.active}if(req.body.password){if(String(req.body.password).length<6)return res.status(400).json({error:'رمز حداقل ۶ کاراکتر'});x.password_hash=bcrypt.hashSync(String(req.body.password),12)}save();audit(req,'update','staff',x.id,`ویرایش کاربر ${x.name}`);const {password_hash,...safe}=x;res.json(safe)});
function attachNames(){return {staff:store.staff.map(({password_hash,...x})=>x),properties:store.properties.map(p=>({...p,assigned_name:store.staff.find(s=>s.id==p.assigned_to)?.name||null})),clients:store.clients.map(c=>({...c,assigned_name:store.staff.find(s=>s.id==c.assigned_to)?.name||null})),followups:store.followups.map(f=>({...f,client_name:store.clients.find(c=>c.id==f.client_id)?.name||null,property_title:store.properties.find(p=>p.id==f.property_id)?.title||null,assigned_name:store.staff.find(s=>s.id==f.assigned_to)?.name||null}))}}
app.get('/api/properties',auth,(req,res)=>res.json(visibleForUser(store.properties,req).map(p=>({...p,assigned_name:store.staff.find(s=>s.id==p.assigned_to)?.name||null})).sort((a,b)=>new Date(b.updated_at)-new Date(a.updated_at))));
app.post('/api/properties',auth,(req,res)=>{const x=req.body||{},t=now();const p={...x,id:next('properties'),lat:x.lat||null,lng:x.lng||null,status:x.status||'active',assigned_to:req.session.user.role==='admin'?(x.assigned_to||null):req.session.user.id,created_by:req.session.user.id,created_at:t,updated_at:t};store.properties.push(p);save();audit(req,'create','property',p.id,`ثبت ملک ${p.title||''}`);res.json({id:p.id})});
app.patch('/api/properties/:id',auth,(req,res)=>{const p=store.properties.find(x=>x.id==req.params.id);if(!p)return res.status(404).json({error:'ملک پیدا نشد'});if(req.session.user.role!=='admin'&&p.assigned_to&&Number(p.assigned_to)!==Number(req.session.user.id))return res.status(403).json({error:'دسترسی ندارید'});Object.assign(p,req.body,{updated_at:now()});save();audit(req,'update','property',p.id,`ویرایش ملک ${p.title||''}`);res.json({ok:true})});
app.delete('/api/properties/:id',admin,(req,res)=>{const i=store.properties.findIndex(x=>x.id==req.params.id);if(i<0)return res.status(404).json({error:'ملک پیدا نشد'});const p=store.properties[i];p.status='inactive';p.updated_at=now();save();audit(req,'archive','property',p.id,`غیرفعال‌سازی ${p.title||''}`);res.json({ok:true})});
app.get('/api/clients',auth,(req,res)=>res.json(visibleForUser(store.clients,req).map(c=>({...c,assigned_name:store.staff.find(s=>s.id==c.assigned_to)?.name||null})).sort((a,b)=>new Date(b.updated_at)-new Date(a.updated_at))));
app.post('/api/clients',auth,(req,res)=>{const x=req.body||{},t=now();const c={...x,id:next('clients'),assigned_to:req.session.user.role==='admin'?(x.assigned_to||null):req.session.user.id,created_by:req.session.user.id,created_at:t,updated_at:t};store.clients.push(c);save();audit(req,'create','client',c.id,`ثبت مشتری ${c.name||''}`);res.json({id:c.id})});
app.patch('/api/clients/:id',auth,(req,res)=>{const c=store.clients.find(x=>x.id==req.params.id);if(!c)return res.status(404).json({error:'مشتری پیدا نشد'});if(req.session.user.role!=='admin'&&c.assigned_to&&Number(c.assigned_to)!==Number(req.session.user.id))return res.status(403).json({error:'دسترسی ندارید'});Object.assign(c,req.body,{updated_at:now()});save();audit(req,'update','client',c.id,`ویرایش مشتری ${c.name||''}`);res.json({ok:true})});
app.post('/api/assign',admin,(req,res)=>{const {entity,id,assigned_to}=req.body||{};const key=entity==='property'?'properties':entity==='client'?'clients':null;if(!key)return res.status(400).json({error:'entity نامعتبر'});const x=store[key].find(v=>v.id==id);if(!x)return res.status(404).json({error:'پرونده پیدا نشد'});x.assigned_to=assigned_to?Number(assigned_to):null;x.updated_at=now();save();audit(req,'assign',entity,x.id,`تخصیص به ${store.staff.find(s=>s.id==x.assigned_to)?.name||'بدون مسئول'}`);res.json({ok:true})});
app.get('/api/followups',auth,(req,res)=>res.json(visibleForUser(store.followups,req).map(f=>({...f,client_name:store.clients.find(c=>c.id==f.client_id)?.name||null,property_title:store.properties.find(p=>p.id==f.property_id)?.title||null,assigned_name:store.staff.find(s=>s.id==f.assigned_to)?.name||null})).sort((a,b)=>String(a.due_at||'').localeCompare(String(b.due_at||'')))));
app.post('/api/followups',auth,(req,res)=>{const x=req.body||{},f={...x,id:next('followups'),status:'open',assigned_to:req.session.user.role==='admin'?(x.assigned_to||null):req.session.user.id,created_by:req.session.user.id,created_at:now()};store.followups.push(f);save();audit(req,'create','followup',f.id,`ثبت پیگیری ${f.title||''}`);res.json({id:f.id})});
app.patch('/api/followups/:id',auth,(req,res)=>{const f=store.followups.find(x=>x.id==req.params.id);if(!f)return res.status(404).json({error:'پیگیری پیدا نشد'});if(req.session.user.role!=='admin'&&f.assigned_to&&Number(f.assigned_to)!==Number(req.session.user.id))return res.status(403).json({error:'دسترسی ندارید'});Object.assign(f,req.body);if(f.status==='done'){f.completed_at=now();f.completed_by=req.session.user.id}f.updated_at=now();save();audit(req,f.status==='done'?'complete':'update','followup',f.id,`پیگیری ${f.title||''}`);res.json({ok:true})});
function score(c,p){let s=0,max=0,why=[];function exact(a,b,w,label){if(a){max+=w;if(b&&String(a).toLowerCase()===String(b).toLowerCase()){s+=w;why.push(label)}}} exact(c.purpose,p.purpose,18,'نوع ملک');exact(c.deal,p.deal,18,'نوع معامله');if(c.city){max+=10;if(String(p.city||'').includes(c.city)){s+=10;why.push('شهر')}}if(c.neighborhood){max+=10;if(String(p.neighborhood||'').includes(c.neighborhood)){s+=10;why.push('محله')}}if(c.min_area||c.max_area){max+=14;let a=Number(p.area);if(a&&(!c.min_area||a>=Number(c.min_area))&&(!c.max_area||a<=Number(c.max_area))){s+=14;why.push('متراژ')}}if(c.min_budget||c.max_budget){max+=16;const v=Number(p.price||0)||Number(p.deposit||0)||Number(p.rent||0);if(v&&(!c.min_budget||v>=Number(c.min_budget))&&(!c.max_budget||v<=Number(c.max_budget))){s+=16;why.push('بودجه')}}if(c.bedrooms){max+=7;if(Number(p.bedrooms)>=Number(c.bedrooms)){s+=7;why.push('خواب')}}if(c.must_have&&p.features){const reqs=String(c.must_have).split(/[,،\s]+/).filter(Boolean),pf=String(p.features).toLowerCase();let hits=reqs.filter(v=>pf.includes(v.toLowerCase())).length;if(reqs.length){max+=7;s+=Math.round(7*hits/reqs.length);if(hits)why.push(`امکانات ${hits}/${reqs.length}`)}}return {score:max?Math.round(s/max*100):0,why}}
app.get('/api/match/:clientId',auth,(req,res)=>{const c=store.clients.find(x=>x.id==req.params.clientId);if(!c)return res.status(404).json({error:'مشتری پیدا نشد'});const ps=visibleForUser(store.properties,req).filter(x=>x.status==='active');res.json(ps.map(p=>({...p,...score(c,p)})).sort((a,b)=>b.score-a.score).slice(0,50))});
app.get('/api/property-matches/:propertyId',auth,(req,res)=>{const p=store.properties.find(x=>x.id==req.params.propertyId);if(!p)return res.status(404).json({error:'ملک پیدا نشد'});res.json(visibleForUser(store.clients,req).map(c=>({...c,...score(c,p)})).sort((a,b)=>b.score-a.score).slice(0,50))});
app.get('/api/search',auth,(req,res)=>{const q=clean(req.query.q).toLowerCase();if(!q)return res.json([]);const terms=q.split(/\s+/).filter(Boolean);const hit=v=>terms.every(t=>String(v||'').toLowerCase().includes(t));const ps=visibleForUser(store.properties,req).filter(x=>[x.title,x.city,x.neighborhood,x.address,x.owner,x.features,x.purpose,x.deal].some(hit)).map(x=>({id:x.id,name:x.title,city:x.city,neighborhood:x.neighborhood,phone:x.phone,type:'ملک'}));const cs=visibleForUser(store.clients,req).filter(x=>[x.name,x.phone,x.city,x.neighborhood,x.must_have,x.purpose,x.deal].some(hit)).map(x=>({id:x.id,name:x.name,city:x.city,neighborhood:x.neighborhood,phone:x.phone,type:'مشتری'}));res.json([...ps,...cs].slice(0,100))});
function dateRange(from,to){const f=from?new Date(from):new Date(Date.now()-30*86400000);const t=to?new Date(to):new Date();t.setHours(23,59,59,999);return {f,t}}
function reportFor(userId,from,to){const {f,t}=dateRange(from,to),acts=store.activities.filter(a=>a.user_id==userId&&new Date(a.created_at)>=f&&new Date(a.created_at)<=t);const props=store.properties.filter(p=>p.assigned_to==userId&&new Date(p.created_at)<=t);const clients=store.clients.filter(c=>c.assigned_to==userId&&new Date(c.created_at)<=t);const fu=store.followups.filter(x=>x.assigned_to==userId&&new Date(x.created_at)<=t);const completed=fu.filter(x=>x.status==='done'&&new Date(x.completed_at||x.updated_at)>=f&&new Date(x.completed_at||x.updated_at)<=t).length;const overdue=fu.filter(x=>x.status==='open'&&x.due_at&&new Date(x.due_at)<new Date()).length;return {user:store.staff.find(s=>s.id==userId)?.name||'نامشخص',from:f.toISOString(),to:t.toISOString(),metrics:{new_properties:props.filter(p=>new Date(p.created_at)>=f).length,new_clients:clients.filter(c=>new Date(c.created_at)>=f).length,followups_created:fu.filter(x=>new Date(x.created_at)>=f).length,followups_completed:completed,followups_overdue:overdue,activity_count:acts.length},activities:acts.slice(-500),followups:fu.filter(x=>new Date(x.created_at)>=f).map(x=>({...x,client_name:store.clients.find(c=>c.id==x.client_id)?.name||null,property_title:store.properties.find(p=>p.id==x.property_id)?.title||null}))}}
app.get('/api/reports/staff/:id',admin,(req,res)=>res.json(reportFor(req.params.id,req.query.from,req.query.to)));
app.get('/api/reports/staff/:id/html',admin,(req,res)=>{const r=reportFor(req.params.id,req.query.from,req.query.to);res.type('html').send(`<!doctype html><html lang="fa" dir="rtl"><meta charset="utf-8"><title>گزارش عملکرد ${r.user}</title><style>body{font-family:Tahoma,Arial;max-width:900px;margin:30px auto;padding:20px;color:#172033}h1{margin-bottom:4px}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.card{border:1px solid #ddd;border-radius:14px;padding:16px}.n{font-size:28px;font-weight:bold}table{width:100%;border-collapse:collapse;margin-top:20px}td,th{padding:9px;border-bottom:1px solid #ddd;text-align:right}@media print{button{display:none}}</style><button onclick="print()">چاپ / ذخیره PDF</button><h1>گزارش عملکرد ${r.user}</h1><p>${r.from.slice(0,10)} تا ${r.to.slice(0,10)}</p><div class="grid">${Object.entries(r.metrics).map(([k,v])=>`<div class="card"><div>${k}</div><div class="n">${v}</div></div>`).join('')}</div><h2>فعالیت‌ها</h2><table><tr><th>زمان</th><th>عملیات</th><th>جزئیات</th></tr>${r.activities.map(a=>`<tr><td>${a.created_at.replace('T',' ').slice(0,19)}</td><td>${a.action}</td><td>${a.details||''}</td></tr>`).join('')}</table></html>`)});
app.get('/api/reports/query',admin,(req,res)=>{const q=clean(req.query.q);if(!q)return res.status(400).json({error:'عبارت گزارش را وارد کنید'});const low=q.toLowerCase();const u=store.staff.find(s=>low.includes(String(s.name||'').toLowerCase()))||store.staff.find(s=>low.includes(String(s.email||'').toLowerCase()));if(!u)return res.status(404).json({error:'پرسنل موردنظر پیدا نشد'});let from,to;const today=new Date();if(/ماه گذشته|ماه اخیر|۳۰ روز|30 روز|یک ماه/.test(q)){from=new Date(today.getTime()-30*86400000);to=today}else{from=new Date(today.getTime()-30*86400000);to=today}res.json(reportFor(u.id,from.toISOString().slice(0,10),to.toISOString().slice(0,10)))});
app.get('/api/activities',admin,(req,res)=>{let a=store.activities.slice().sort((x,y)=>new Date(y.created_at)-new Date(x.created_at));if(req.query.user_id)a=a.filter(x=>x.user_id==req.query.user_id);res.json(a.slice(0,500))});
app.get('/api/dashboard',auth,(req,res)=>{const uid=req.session.user.id,today=new Date().toISOString().slice(0,10);const ps=visibleForUser(store.properties,req),cs=visibleForUser(store.clients,req),fsu=visibleForUser(store.followups,req);res.json({properties:ps.filter(x=>x.status==='active').length,clients:cs.length,openFollowups:fsu.filter(x=>x.status==='open').length,todayFollowups:fsu.filter(x=>x.status==='open'&&String(x.due_at||'').slice(0,10)===today).length,overdue:fsu.filter(x=>x.status==='open'&&x.due_at&&new Date(x.due_at)<new Date()).length,newProperties:ps.filter(x=>new Date(x.created_at)>new Date(Date.now()-7*86400000)).length,newClients:cs.filter(x=>new Date(x.created_at)>new Date(Date.now()-7*86400000)).length,staff:store.staff.filter(x=>x.active).length,activities:store.activities.slice(-10).reverse()})});
app.get('/api/backup',admin,(req,res)=>{res.setHeader('Content-Disposition',`attachment; filename="amlak-backup-${new Date().toISOString().slice(0,10)}.json"`);res.json(store)});
app.post('/api/restore',admin,(req,res)=>{const d=req.body;if(!d||!Array.isArray(d.staff)||!Array.isArray(d.properties)||!Array.isArray(d.clients)||!Array.isArray(d.followups))return res.status(400).json({error:'فایل پشتیبان معتبر نیست'});store={...empty(),...d,schema_version:SCHEMA_VERSION,activities:Array.isArray(d.activities)?d.activities:[],seq:{...empty().seq,...(d.seq||{})}};save();audit(req,'restore','system',0,'بازیابی پشتیبان');res.json({ok:true})});
app.get('/api/share',admin,(req,res)=>{const host=`${req.protocol}://${req.get('host')}`;res.json({url:host,login_url:host+'/#login',note:'دسترسی فقط با حساب‌های فعال سیستم ممکن است.'})});
app.use(express.static(path.join(__dirname,'public')));app.get('*',(req,res)=>res.sendFile(path.join(__dirname,'public/index.html')));
app.listen(PORT,'0.0.0.0',()=>console.log(`Amlak AI Office v${SCHEMA_VERSION} running on ${PORT}`));
